bcc: Autospec creation for update from version 0.12.0 to version 0.13.0
Alban Crequy (3):
      tools: cgroup filtering in execsnoop/opensnoop
      tools/trace.py: flush stdout for each event
      tools: fix confusion between execsnoop and opensnoop

Andrii Nakryiko (3):
      libbpf tools: check in bpftool for use by libbpf-based tool build
      tools: add vmlinux.h header with all kernel types
      tools: add libbpf-based tools to BCC w/ runqslower as first converted tool

Anton Protopopov (2):
      bpflist: list only real bpf objects
      bpflist: use smarter print format

Caspar Zhang (1):
      fix libbpf_uapi path typo

Colin Ian King (1):
      snapcraft: add missing libfl-dev dependency

Dale Hamel (4):
      Remove namespace code from libbpf to fix USDT
      Run BCC test suite with github actions
      Make inode-only matching default, reverse USDT kludge
      Allow specifying clang base directory

DavadDi (2):
      fix line TypeError
      fix pid filter bug

Felix Geisendörfer (1):
      fix -h output for --sort option

Gary Lin (1):
      docs: add BPF trampoline to the kernel features

Gergely Bod (1):
      tools/offcputime.py: Redundatn arg check

Gil Raphaelli (1):
      tools/profile: fix kernel delimiter when folding (#2758)

Giovanni Tataranni (1):
      remove dead link

Itay Shakury (1):
      correctly describe installation situation for Ubuntu

Ivan Babrou (1):
      Package static archives, closes #1938

Jiri Olsa (1):
      tools/klockstat.py: Do not display symbol twice for stack

John Gallagher (1):
      libbcc debian package is architecture-dependent

Marko Myllynen (1):
      klockstat: fix caller filter

Masanori Misono (1):
      docs: Remove a redundant space

Michael Prokop (1):
      Fix a bunch of typos (#2693)

Michael Wuertinger (2):
      Add Ubuntu Eon incompatibility note
      Ubuntu Eon build dependencies and version numbers

Paul Chaignon (4):
      Remove kretprobe__ prefix from program names
      man: fix required kernel version in man pages
      Links to 3 articles on Linux tracing using bcc
      rewriter: Fix tracking of pointers with several indirections

Pavel Dubovitsky (1):
      bindsnoop BCC tool (#2749)

Rohan Garg (1):
      tools/stackcount: Fix address resolution for user-space stack

Russell Jones (1):
      Fix CentOS 6 support.

Sergio Schvezov (1):
      snap: update and cleanup snapcraft.yaml

Sevan Janiyan (1):
      Improve wording on how latency is measured

Shmulik Ladkani (1):
      bcc.BPF.cleanup(): Ensure self.funcs items get deleted during cleanup

Stefan Raspl (1):
      Fix s390 kprobes support

Tu (1):
      Add XSKMAP support (#2730)

Török Edwin (1):
      Secure Boot:  physical keypress to disable lockdown

Vladislav Bogdanov (1):
      Fix offwaketime regression introduced by #ac00ac5

Wenbo Zhang (1):
      add tool: compactsnoop

Yonghong Song (19):
      sync with latest libbpf
      change version.cmake to check all tags
      fix test_map_in_map.cc compilation error
      sanitize btf VAR and DATASEC types
      support BPF_MAP_TYPE_SK_STORAGE map
      avoid complex expression in struct member initializer
      sanitize BTF_KIND_FUNC
      sync with latest libbpf repo
      fix llvm compilation error
      sync with latest libbpf repo
      fix a bug in networking/simulation.py
      sync to latest libbpf repo
      fix compilation error due to latest llvm change
      define CC_USING_FENTRY if CONFIG_FUNCTION_TRACER is defined
      prevent rewriting for array element type
      Do not rewrite array subscripts if invalid sourceloc range
      support sockmap/sockhash/cgroup_local_storage maps
      sync to latest libbpf
      debian changelog for v0.13.0 tag

bodgergely (1):
      tools/runqslower.py: Option for --pid or --tid (#2635)

jnach (1):
      Update dddos.py

mtmn (1):
      Remove  from list of AUR packages

yonghong-song (1):
      update usage of MCInstPrinter printInst() for llvm10 (#2696)