bcc: Autospec creation for update from version 0.25.0 to version 0.27.0
Adrián Moreno (1):
      bcc: Fix multi-word array type handling (#4412)

Alan Maguire (2):
      bcc: support building with external libbpf package and older uapi linux/bpf.h
      bcc: and generated compat/linux/bpf.h to .gitignore

Alex (3):
      build: harden bcc-test.yml permissions
      build: harden publish.yml permissions
      build: harden publish-build-containers.yml permissions

Alvin (1):
      Update INSTALL.md

Borko Jandras (1):
      Fix for incomplete static libraries.

CSWYF3634076 (1):
      libbpf-tools/solisten: modify port type (#4386)

Cathy Zhang (3):
      libbpf-tools/cpufreq: Fix the initialization of freqs_mhz
      libbpf-tools/cpufreq: Rename init_freqs_hmz as init_freqs_mhz
      libbpf-tools: Don't print CPU frequency if count is zero

Chen Yaqi (1):
      libbpf-tools/tcprtt: Fix out-of-bounds accessing of inet_sock struct.

Chethan Suresh (2):
      Support libbpf-tools based capable tool
      docs/kernel_config.md: kernel configs required for eBPF

Cimon Lucas (LCM) (1):
      INSTALL.md - Use a faster & smaller shallow clone when fetching WSL2-Linux-Kernel git repo

Curu Wong (3):
      tools: add filegone to trace why file gone (#4333)
      tools/runqslower: replace invalid delete operation by zero update
      tools/syscount: add --ppid option

Daniel Kobras (1):
      tools/nfsslower: fix on v3-only systems

Dave Marchevsky (5):
      [test_infra] Add systemtap devel header and ruby to fedora docker
      test_bpf_table: Re-add deletion of 'bpf' module
      test_tools_smoke.py: mayFail test_offwaketime
      GH Actions: Stop publishing to quay.io
      Revert libbpf submodule to latest intentional change

Delyan Kratunov (1):
      Allow libdebuginfod to be excluded even if present

Eunseon Lee (1):
      libbpf-tools/offcputime: Add dso info and symbol offset to backtrace for -v option

Francis Laniel (2):
      libbpf-tools: Add tcptop tool.
      libbpf-tools: Add biotop tool.

Furkan Türkal (1):
      docs: add installation method for Debian - Binary (#4378)

Gabriele Santomaggio (1):
      Add missing examples files (#4312)

Hailong Liu (3):
      libbpf-tools/runqlen: Add runq lenth of host's rq
      libbpf-tools/softirqs: Add event counts report
      libbpf-tools/wakeuptime: Fix the type of the value

Harsh Prateek Bora (1):
      tools: Introducing ppchcalls.py for hcall count/latency stats.

Hengqi Chen (26):
      libbpf-tools: Update bpftool submodule
      libbpf-tools: Allow runq tools to run on old kernels
      libbpf-tools/klockstat: Fallback to kprobe if fentry is not available
      libbpf-tools: Add tcpstates
      bcc: Bump CMake minimum version to 2.8.12
      libbpf-tools: Allow hardirqs to run on old kernels
      libbpf-tools: Allow softirqs to run on old kernels
      Revert "Use absolute module file path when possible"
      libbpf-tools: Add feature probe for BPF ring buffer
      libbpf-tools: Add support for bpf_ringbuf
      libbpf-tools: Introduce BPF ring buffer to mountsnoop
      libbpf-tools: Enable biolatency on kernels without BPF trampoline
      libbpf-tools/gethostlatency: Extract libc.so path from /proc/self/maps
      libbpf-tools: Use bpf_probe_read_kernel{,_str} instead
      libbpf-tools/opensnoop: Disable BPF program if tracepoint not exists
      libbpf-tools/statsnoop: Trace all stat syscall variants
      docs/kernel-versions.md: Replace korg links with GitHub links
      libbpf-tools: Enable mdflush on kernels without fentry support
      libbpf-tools: Enable drsnoop on kernels without BPF trampoline
      libbpf-tools: Detect kernel/modules BTF using libbpf APIs
      libbpf-tools: Remove use of reallocarray
      libbpf-tools: Fix tracepoint existence check in statsnoop
      tools: Fix filelife for kernels without CONFIG_SECURITY
      bcc: Sync with latest libbpf repo
      libbpf-tools: Add loongarch support
      libbpf-tools: Drop libbpf_set_strict_mode() calls

Huang Huang (1):
      libbpf-tools/tcplife: fix filter by ports

Ian Rogers (1):
      libbpf-tools: fix biosnoop exit code

Ism Hong (1):
      runqslower: create sufficiently large array table to avoid missing tasks

Ivan Babrou (2):
      libbpf-tools/klockstat: print the lock info for max acq/hold times
      libbpf-tools/klockstat: accept lock addr as well as lock name

Jerome Marchand (6):
      Fix some documentation issues (#4197)
      Fix clang 15 int to pointer conversion errors
      libbpf: Allow kernel_struct_has_field to reach field in unnamed struct or union
      Fix get_kprobe_functions
      killsnoop: add missing -s and -T options to the synopsis
      Porting from distutils to setuptools

Kenta Tada (1):
      docs/kernel_config.md: add the config for kprobe multi (#4448)

Khem Raj (1):
      tests/cc: Use c++14 standard

Kosuke Tatsukawa (1):
      Print slow commit operations in nfsslower

Krisztian Fekete (3):
      add bpf_ringbuf support to oomkill example
      move timeout to compat header from mountsnoop.c
      make warnings consistent by switching to fprintf everywhere

Kui-Feng Lee (1):
      Show the stacktrace of the userspace in opensnoop.

Lars Gohr (1):
      Updated elgohr/Publish-Docker-Github-Action to a supported version (v5)

Marcelo Juchem (1):
      fix arithmetic on a pointer to an incomplete type

Matheus Castanho (1):
      docs: Fix GPL flag for BPF_FUNC_ktime_get*_ns (#4421)

Mauricio Vásquez (2):
      docs: Fix kernel version for BPF_FUNC_ktime_get_boot_ns()
      docs: Update links to use Github

Michal Gregorczyk (13):
      extract kheaders to $TMPDIR directory
      Add absraction hiding source of elf files
      Make find_debug_file return debug sos via elf_file
      Support mini debug info files.
      install xz and liblzma in Dockerfile.ubuntu
      tests for all kinds of debuginfo lookups
      call elf_end in bcc_elf_foreach_vdso_sym
      Implement basic zip archive parsing.
      Support address lookup for zipped libs.
      Recognize zipped libraries when parsing maps.
      Make bpf_attach_uprobe recognize zipped libraries.
      Install zip in test environment
      bcc_zip_archive_open should not loop indefinitely for bad archives

Michał Gregorczyk (1):
      Use /sys/kernel/tracing when debugfs is not available (#4216)

Namhyung Kim (1):
      libbpf-tools: Fix klockstat to finish with -R

Nathan Scott (2):
      libbpf-tools: update arm vmlinux with missing perf_event, BPF_PROG_TYPE_PERF_EVENT
      libbpf-tools: update ppc vmlinux.h with missing bpf_perf_link, BPF_LINK_TYPE_PERF_EVENT

Nicolas Sterchele (1):
      libbpf-tools: convert wakeuptime tool

Nurdan Almazbekov (1):
      Fix file names being empty (#4293)

Rong Tao (21):
      Add cmake TARGET: uninstall
      Check whether cargo exists and disable the blazesym feature. (#4227)
      Fix libbpf-tools/sigsnoop segment fault (#4228)
      Missing a newline('\n')
      tools/filegone: Check btf struct field instead of KERNEL_VERSION macro
      tools: filelife: Check btf struct field for CO-RE and add vfs_open()
      libbpf-tools: fsdist,fsslower: Fix redefinition of enumerator 'OPEN'
      libbpf-tools/ksnoop: remove always 'true' statement
      tools/ttysnoop: Fix kfunc Unknown error
      libbpf-tools: filelife: Check btf struct field for CO-RE and add vfs_open()
      bcc.spec: Only python2 need python2-devel (#4400)
      tools/ttysnoop: Add ITER_UBUF support
      tools/ttysnoop: Fix uninitialized 'buf' error
      libbpf-tools/cachestat: Fix failed to attach: ERROR: strerror_r(-524)=22
      tools/readahead: Fix: Failed to attach BPF program entry__do_page_cache_readahead
      libbpf-tools/numamove: Fix failed to attach: ERROR: strerror_r(-524)=22
      tools/slabratetop: Fix error: incomplete definition of type 'struct slab'
      tools/compactsnoop.py: Fix raw_tracepoint Invalid argument error
      tools/nfsslower.py: Fix uninitialized struct pad error
      libbpf-tools/cachestat: Introduce tracepoint writeback_dirty_{page,folio}
      tools/{cachetop,cachestat}: Introduce tracepoint writeback_dirty_{page,folio}

Rui Cao (1):
      Fix padding field not initialized issue

Ryan Cheng (1):
      Truncate long uprobe names and append its hash for differentiation (#4442)

Shay Drory (1):
      tools/memleak: Remove deleted trace points (kernels >=6.1)

Shung-Hsi Yu (1):
      NULL check CallExpr.getCalleeDecl()

Sumanth Korikkar (1):
      clang/b_frontend_action: fix arch_syscall_wrapper (#4390)

Tomas Glozar (3):
      Fix ProcStat::is_stale for gone PIDs
      Use absolute module file path when possible
      Improve ProcSyms module path handling

Will Daly (1):
      Edit WSL2 install instructions

Y7n05h (1):
      Use explicit type conversion for void * to u64.

Yonghong Song (12):
      Fix bpf_pseudo_fd() type conversion error
      Fix a llvm signed division error for compactsnoop tool
      Sync with latest libbpf repo
      Fix a llvm16 compilation error
      Sync with latest libbpf repo
      Fix a llvm compilation error
      Sync with latest libbpf repo
      Update debian changelog for release v0.26.0
      Set cmake policy for CMP0057
      Fix compilation error when built with llvm17
      Fix a typo in changelog
      Update debian changelog for release v0.27.0

Zang MingJie (1):
      cmake: Follow PEP 440 local version

agentzex (1):
      examples/networking: add tcp_mon_block (#4459)

chantra (29):
      [test] Fix Wrapper script to properly handle arguments
      [test][sockhash/map] Fix the test to work with kernels >= 5.15
      Attempt to find kernel's linux/version.h for the running kernel
      [test][usdt_probes][bionic] kill child manually
      [test] fix module search test
      [tests] fix python tests
      [test][bionic] Force python3 and utf-8 encoding
      Revert "test_tools_smoke.py: mayFail test_offwaketime"
      [build] Move docker files used for build CI in their own directory
      [ci] new workflow to publish CI build containers
      [ci] Remove ruby build artifacts from docker images
      [ci][docker] Change env varibable names so they are not bound to ubuntu
      [ci] Upgrade to ruby-installer 0.8.4 and ruby 3.1.2
      [ci][dcoker] Make Fedora version controlled by env variable
      [ci] Add support for Fedora 36 container
      [scripts] Update git-clang-format
      [ci] make build CI use docker images from this repo registry
      [python][test] change traced syscall from clone to execve
      [test][python] temptatively attach to blk_start_request probe.
      [biosnoop] Revert #4124
      [ci] Install netperf and iperf
      [actions] Trigger publish-build-containers workflow on PR without pushing
      [ci] Enable running CI on Fedora 36
      [test][python] Clear deprecation warnings
      [actions] Refactor building and pushing docker containers
      [actions] Build docker container when Dockerfile are modified
      [docker] Fix tabs in Dockerfile.fedora
      [testing] add skipUnlessHasBinaries decorator
      [test][test_brb] Gate the test behind the new skipUnlessHasBinaries decorator

chentao.ct (1):
      libbpf-tools: Add javagc monitor

dongruihua.drh (1):
      docs/tutorial.md: fix typo

duongmn89 (1):
      Delete unused variable

inwardvessel (1):
      convert memleak to libbpf

jackygam2001 (1):
      support tracepoint for tcp_set_ca_state

james.chu (1):
      fix the Makefile of libbpf-tools, make it support cross compile (#4429)

log2 (1):
      delete 1 line redundant code for WSL2.

maliubiao (1):
      fix undefined reference reallocarray

michael-chuh (1):
      tools/ttysnoop: Fix wrong KERNEL_VERSION (#4366)

mickey_zhu (1):
      tools/ttysnoop: add ringbuf

rockyxing (2):
      tools/opensnoop: Allow to set size of the perf ring buffer (#4219)
      tools/statsnoop: Add some stat() variants (#4367)

root (2):
      update Lesson 3 example code for KeyboardInterrupt
      update Lesson 4 example code for KeyboardInterrupt

wenlxie (1):
      Fix the uid not defined issue

woodpenker (5):
      wakeuptime: remove unused global var `exiting`
      offcputime: remove unused global var `exiting`
      libbpf-tools: use BPF_KPROBE/BPF_KRETPROBE in gethostlatency/ksnoop. (#4347)
      offcputime: fix no comm&delta output if missed user stack
      libbpf-tools/cpudist: Allow cpudist to run on old kernels

xingfeng2510 (12):
      tools/trace: Fix TypeError when format string contains %K or %U
      tools/execsnoop: Add PPID filter support
      tools/trace: Decode bytes to str
      tools/trace: Remove explicit ctype cast
      tools/opensnoop: Allow to show full path for an open file with relative path
      tools/biosnoop: Fix a typo
      tools/biopattern: improve the output of biopattern
      tools/vfsstat: Add PID filter support
      tools/biosnoop: Add support for displaying block I/O pattern
      tools/argdist: Add ebpf option to print BPF program code only
      tools/cpudist: Bugfix incorrect cpu key when pid not equal to 0
      tools/offcputime: Add option to show symbol offsets

yangxingwu (2):
      bcc/python: remove additional space
      tools/tcpsynbl.py: several small improvements of coding style (#4415)

yezhem (1):
      tools/memleak: fix print_outstanding_combined func, exception has occurred: TypeError in python

yifeifang (1):
      update WSL2 install instruction (#4423)

yunwei37 (1):
      libbpf-tools: fix uprobe helper possible overflow

yzhao (1):
      Added bounded loop into the main bpf features list

zhenwei pi (3):
      tools: killsnoop: support target PID filter
      tools: killsnoop: auto detect the length of PID/TPID column
      tools/runqslower: fix '-P'&'-p PID' conflict

zhq (1):
      update python developer tutorial (#4194)